### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JupiterRider** [maxpoletaev/directcgo#1]
Hey @maxpoletaev,

would it be possible to give this project a permissive license (MIT, zlib, BSD, Apache)?

Thanks in advance!

**Comment by maxpoletaev** [comment]
There is absolutely no code that is worth copyrighting. So consider it public domain, I guess. I will add that later to the repo.

After all, it's more like an idea, inspired by fastcgo/rustgo and the go runtime code, that you can try and adjust for your needs, rather than a final solution.

**Comment by maxpoletaev** [comment]
Alright, I've added the license text. All further versions will be using zlib license text as I've got a few ideas with the assembly code generation, which might not be that trivial.
